export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const RECEIVED_MEASUREMENT = "EVENT/RECEIVED_MEASUREMENT";
export const FLARE_TEMP_BUTTON_TOGGLE = "EVENT/FLARE_TEMP_BUTTON_TOGGLE";
